import { ProfileModel } from '../models/profile.model';

export const crewCollection: ProfileModel[] = [
  {
    _id: Math.random(),
    bio: 'Some Random Biography',
    coverImage: {
      bytes: 0,
      fileFolder: '',
      fileId: '',
      fileLink: '',
      fileName: '',
      fileSizeInMbs: 0,
      fileType: '',
    },
    createdon: 'Tue Nov 07 2023 11:28:51 GMT+0200 (South Africa Standard Time)',
    crew_id: '786024846582177',
    discography: [
      {
        art: {
          bytes: 0,
          fileFolder: '',
          fileId: '',
          fileLink: '',
          fileName: '',
          fileSizeInMbs: 0,
          fileType: '',
        },
        contributes: [],
        genre: '',
        reviews: [
          {
            rating: 4,
            reviewDate: '',
            reviewer: '',
            reviewId: '',
            reviewText: '',
          },
        ],
        title: '',
        trackId: '',
        type: '',
        urls: [
          {
            color: '',
            platform: '',
            platformIcon: '',
            url: '',
          },
        ],
        year: 0,
        artist: "" 
      },
    ],
    gallery: [
      {
        bytes: 0,
        fileFolder: '',
        fileId: '',
        fileLink: '',
        fileName: '',
        fileSizeInMbs: 0,
        fileType: '',
      },
    ],
    gender: 'Male',
    image: {
      bytes: 495616,
      fileFolder: 'crew',
      fileId: '6028158978309033',
      fileLink: 'http://localhost:4200/assets/images/makhanda.jpg',
      fileName: 'makhanada',
      fileSizeInMbs: 0.4,
      fileType: 'image/jpg',
    },
    isPrivate: true,
    isSuspended: true,
    lastused: 'Tue Nov 07 2023 11:28:51 GMT+0200 (South Africa Standard Time)',
    name: 'Enkosi Tsotsa',
    socials: [
      {
        active: true,
        platform: '',
        socialId: '',
        url: '',
        username: '',
      },
    ],
    tag: 'MakhandaZonke ZA',
    status: '',
    type: 'artist',
    tags: ['CEO', 'Music Producer', 'Sound Engineer'],
  },
  {
    _id: Math.random(),
    bio: 'Some Random Biography',
    coverImage: {
      bytes: 0,
      fileFolder: '',
      fileId: '',
      fileLink: '',
      fileName: '',
      fileSizeInMbs: 0,
      fileType: '',
    },
    createdon: 'Tue Nov 07 2023 11:28:51 GMT+0200 (South Africa Standard Time)',
    crew_id: '786024846582177',
    discography: [
      {
        art: {
          bytes: 0,
          fileFolder: '',
          fileId: '',
          fileLink: '',
          fileName: '',
          fileSizeInMbs: 0,
          fileType: '',
        },
        contributes: [],
        genre: '',
        reviews: [
          {
            rating: 4,
            reviewDate: '',
            reviewer: '',
            reviewId: '',
            reviewText: '',
          },
        ],
        title: '',
        trackId: '',
        type: '',
        urls: [
          {
            color: '',
            platform: '',
            platformIcon: '',
            url: '',
          },
        ],
        year: 0,
        artist: ""
      },
    ],
    gallery: [
      {
        bytes: 0,
        fileFolder: '',
        fileId: '',
        fileLink: '',
        fileName: '',
        fileSizeInMbs: 0,
        fileType: '',
      },
    ],
    gender: 'Male',
    image: {
      bytes: 495616,
      fileFolder: 'crew',
      fileId: '6028158978309033',
      fileLink: 'http://localhost:4200/assets/images/xolelani.jpg',
      fileName: 'xolelani',
      fileSizeInMbs: 0.4,
      fileType: 'image/jpg',
    },
    isPrivate: true,
    isSuspended: true,
    lastused: 'Tue Nov 07 2023 11:28:51 GMT+0200 (South Africa Standard Time)',
    name: 'Xolelani Mtana',
    socials: [
      {
        active: true,
        platform: '',
        socialId: '',
        url: '',
        username: '',
      },
    ],
    tag: 'Xolelani',
    status: '',
    type: 'COO',
    tags: ['COO', 'Music Producer', 'Sound Engineer'],
  },
  {
    _id: Math.random(),
    bio: 'Some Random Biography',
    coverImage: {
      bytes: 0,
      fileFolder: '',
      fileId: '',
      fileLink: '',
      fileName: '',
      fileSizeInMbs: 0,
      fileType: '',
    },
    createdon: 'Tue Nov 07 2023 11:28:51 GMT+0200 (South Africa Standard Time)',
    crew_id: '786024846582177',
    discography: [
      {
        art: {
          bytes: 0,
          fileFolder: '',
          fileId: '',
          fileLink: '',
          fileName: '',
          fileSizeInMbs: 0,
          fileType: '',
        },
        contributes: [],
        genre: '',
        reviews: [
          {
            rating: 4,
            reviewDate: '',
            reviewer: '',
            reviewId: '',
            reviewText: '',
          },
        ],
        title: '',
        trackId: '',
        type: '',
        urls: [
          {
            color: '',
            platform: '',
            platformIcon: '',
            url: '',
          },
        ],
        year: 0,
        artist: ""
      },
    ],
    gallery: [
      {
        bytes: 0,
        fileFolder: '',
        fileId: '',
        fileLink: '',
        fileName: '',
        fileSizeInMbs: 0,
        fileType: '',
      },
    ],
    gender: 'Male',
    image: {
      bytes: 495616,
      fileFolder: 'crew',
      fileId: '6028158978309033',
      fileLink: 'http://localhost:4200/assets/images/dericho.jpg',
      fileName: 'dericho',
      fileSizeInMbs: 0.4,
      fileType: 'image/jpg',
    },
    isPrivate: true,
    isSuspended: true,
    lastused: 'Tue Nov 07 2023 11:28:51 GMT+0200 (South Africa Standard Time)',
    name: 'Asemahle Tostsa',
    socials: [
      {
        active: true,
        platform: '',
        socialId: '',
        url: '',
        username: '',
      },
    ],
    tag: 'De Richo',
    status: '',
    type: 'Music Artist',
    tags: ['Music Artist', 'Music Producer', 'Sound Engineer'],
  },
];
